# Project identity
sonar.projectKey=FIAP-15SOAT_oficina_mecanica_grupo39
sonar.organization=fiap-15soat
sonar.projectName=oficina_mecanica_grupo39
# sonar.projectVersion=1.0

# Analysis scope
sonar.sources=src
sonar.tests=test
sonar.exclusions=node_modules/**,dist/**,coverage/**,prisma/generated/**,src/**/*.module.ts,src/main.ts,src/domain/enums/**,src/infrastructure/database/prisma/**,src/**/*.config.ts,src/**/*.exception.ts,src/**/*.dto.ts
sonar.test.inclusions=**/*.spec.ts

# TypeScript
sonar.typescript.tsconfigPaths=tsconfig.json

# Coverage
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Encoding
# sonar.sourceEncoding=UTF-8