# Project identity
sonar.projectKey=FIAP-15SOAT_oficina_mecanica_grupo39
sonar.organization=fiap-15soat
sonar.projectName=oficina_mecanica_grupo39
# sonar.projectVersion=1.0

# Analysis scope
sonar.sources=src
sonar.tests=test
sonar.exclusions=node_modules/**,dist/**,coverage/**,prisma/generated/**
sonar.test.inclusions=**/*.spec.ts,**/*.e2e-spec.ts

# TypeScript
sonar.typescript.tsconfigPaths=tsconfig.json

# Encoding
# sonar.sourceEncoding=UTF-8