apiVersion: batch/v1
kind: Job
metadata:
  name: JOB_NAME_PLACEHOLDER
  namespace: oficina
  labels:
    app.kubernetes.io/name: db-migrate-job
    app.kubernetes.io/part-of: oficina-mecanica
spec:
  ttlSecondsAfterFinished: 1209600
  backoffLimit: 0
  template:
    metadata:
      labels:
        app.kubernetes.io/name: db-migrate-job
        app.kubernetes.io/part-of: oficina-mecanica
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: IMAGE_URI_PLACEHOLDER
          imagePullPolicy: Always
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: api-secret
                  key: DATABASE_URL
          command:
            - sh
            - -c
            - |
              npx prisma migrate deploy
              npx prisma db seed
