apiVersion: v1
kind: Secret
metadata:
  name: api-secret
  namespace: oficina
  labels:
    app.kubernetes.io/name: oficina-api
    app.kubernetes.io/part-of: oficina-mecanica
type: Opaque
stringData:
  DATABASE_URL: postgresql://postgres:${CHANGE_ME_STRONG_PASSWORD}@postgres.oficina.svc.cluster.local:5432/techchallenge?schema=public
  JWT_SECRET: ${JWT_SECRET}
  JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
  QUOTE_DECISION_TOKEN_SECRET: ${QUOTE_DECISION_TOKEN_SECRET}