apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: oficina
  labels:
    app.kubernetes.io/name: oficina-api
    app.kubernetes.io/part-of: oficina-mecanica
data:
  NODE_ENV: production
  PORT: "3000"
