apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: oficina
  labels:
    app.kubernetes.io/name: oficina-api
    app.kubernetes.io/part-of: oficina-mecanica
data:
  NODE_ENV: production
  PORT: "3000"
  JWT_EXPIRATION: "15m"
  JWT_REFRESH_EXPIRATION: "7d"
  BCRYPT_SALT_ROUNDS: "12"
  MAIL_HOST: "mailhog"
  MAIL_PORT: "1025"
  TZ: "America/Sao_Paulo"
  LOG_LEVEL: "info"
  OTEL_SERVICE_NAME: "oficina-mecanica-api"
  OTEL_SERVICE_NAMESPACE: "oficina-mecanica"
  TRUSTED_PROXY_CIDRS: ""
  CUSTOMER_JWT_ISSUER: "oficina-customer-auth"
  CUSTOMER_JWT_AUDIENCE: "oficina-api"
