apiVersion: v1
kind: Secret
metadata:
  name: datadog-secret
  namespace: oficina
  labels:
    app.kubernetes.io/name: datadog-agent
    app.kubernetes.io/part-of: oficina-mecanica

type: Opaque
stringData:
  DD_API_KEY: ${DD_API_KEY}
