# Project identity
sonar.projectKey=FIAP-15SOAT_oficina-mecanica-app
sonar.organization=fiap-15soat
sonar.projectName=oficina-mecanica-app
# sonar.projectVersion=1.0

# Analysis scope
sonar.sources=src
sonar.tests=test
sonar.exclusions=node_modules/**,dist/**,coverage/**,prisma/generated/**,src/**/*.module.ts,src/main.ts,src/domain/enums/**,src/infrastructure/persistence/prisma/prisma.service.ts,src/**/*.config.ts,src/**/*.exception.ts,src/**/*.dto.ts,src/domain/constants/**
sonar.test.inclusions=**/*.spec.ts

# TypeScript
sonar.typescript.tsconfigPaths=tsconfig.json

# Coverage
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Quality gate — wait for the gate result and fail the job if it is not passed.
sonar.qualitygate.wait=true

# Encoding
# sonar.sourceEncoding=UTF-8
